version: '3.6'

services:
  app:
    build: .
    working_dir: /app
    command: rspec
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env.dev
      - .env
  redis:
    image: "redis:alpine"
    container_name: redis-cq
    ports:
      - "${REDIS_LOCAL_PORT:-6379}"
      - "${REDIS_PORTS:-$REDIS_LOCAL_PORT:6379}"
    volumes:
      - $PWD/redis-data:/data:delegated
volumes:
  redis:
